name: CI
on:
  # Only run when merging to master, or open/synchronize/reopen a PR.
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6

      - name: Unit test
        run: |
          sleep 30
          python -m unittest

  ci-success:
    name: ci
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
